CREATE TABLE IF NOT EXISTS c_pages_route
(
    ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT,
    ACTIVE VARCHAR(1) DEFAULT 'N',
    ROUTE_DOMAIN VARCHAR (255) DEFAULT NULL,
    ROUTE_PATH VARCHAR (255) NOT NULL,
    CONTENT_TYPE VARCHAR (255) NOT NULL,
    PAGE_PROPERTIES TEXT DEFAULT NULL,
    COMPONENT_NAME VARCHAR (255) DEFAULT NULL,
    COMPONENT_PARAMS TEXT DEFAULT NULL,
    COMPONENT_TEMPLATE VARCHAR (255) DEFAULT NULL,
    HTML_CONTENT TEXT DEFAULT NULL,
    INCLUDE_PATH VARCHAR (255) DEFAULT NULL,
    REDIRECT_URL VARCHAR (255) DEFAULT NULL,
    DATE_CREATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATE_MODIFY DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);
